SPiN-Lab/connPFM

- connPFM/utils/atlas_mod.py
> [ENH] Do not apply inverse transform if not necessary

- .circleci/config.yml
- connPFM/deconvolution/roiPFM.py
Closes #33  .
- Deletes all reference to previous personal repository
- uses official connpfm repo
> Start using connpfm official docker repository

- connPFM/debiasing/debiasing_functions.py
- connPFM/tests/conftest.py
- connPFM/tests/test_debiasing.py
Closes # .
- Adds testing to the debiasing functions
-
> Add debiasing testing 

- connPFM/tests/test_deconvolution.py
Closes # .
-  Add testing to slars_stability.py
-
>  Add testing to slars_stability.py

- .circleci/config.yml
- Makefile
- connPFM/deconvolution/stability_lars.py
- connPFM/tests/conftest.py
- connPFM/tests/test_integration.py
Closes #37 .
- add tests for the different workflows in the pipeline pfm,ev and debias
- pfm integration is done only with one ROI reducing the computational cost of testing
> add Integration tests to the toolbox

- .circleci/config.yml
- docker_slim/Dockerfile
Closes #34  .
- add a filter of branch inside the build_trial_job
- use the branch in circle CI to build the docker image both for the trial and for the latest build
> Build docker with current brach for both PRs and main branches

- ohbm2022/plots_ohbm.py
> add figure one for OHBM 

- .circleci/config.yml
- docker_slim/Dockerfile
Closes # .
- mataints the cache for the installation
- timeout limit for integration tests 20 min
> don't delete cache docker image

- connPFM/connectivity/ev.py
- connPFM/debiasing/debiasing.py
- ohbm2022/plots_ohbm.py
Closes # .
- use signal percentage change in debiasing
- change the edge matrix figure for OHBM
- save txt and 1d files from rss and edge timepoints
> add last changes for OHBM2022

- connPFM/cli/connPFM.py
- connPFM/connPFM.py
- connPFM/debiasing/debiasing.py
Closes #55.
- Add `groups` and `distance` options for debiasing with groups.
- Move debug and quiet modes to the end of CLI.
- Pass `groups` and `distance` arguments to debiasing functions.
> Add group and distance options to CLI

- connPFM/debiasing/debiasing.py
- connPFM/deconvolution/roiPFM.py
- connPFM/utils/atlas_mod.py
- connPFM/utils/surrogate_generator.py
Closes # .
- now we check the space with 3dinfo,
- If the space is `TLRC` then changes the space to `ORIG`
> Modify inverse_transform so it works properly

- connPFM/debiasing/debiasing.py
- connPFM/deconvolution/roiPFM.py
- connPFM/deconvolution/stability_lars.py
Closes # 59.
- Removes standardization from all maskers (the one in `ev.py` was already set to `False` apparently).
> Remove standardizing to psc from all maskers.

- connPFM/tests/conftest.py
Closes #61  .
- Now the testing input is in SPC 
- Therefore all the osf outputs have been change so the data can be compared properly
> change OSF input file to SPC

- connPFM/connectivity/connectivity_utils.py
- connPFM/connectivity/ev.py
Closes none.
- Calculate sum outside of `calculate_hist_threshold`.
> Fix time-locked ETS thresholding bug

- connPFM/connectivity/connectivity_utils.py
- connPFM/connectivity/ev.py
- connPFM/tests/test_ev.py
Closes #53 .
- Remove second calculation of surrogate matrices.
- Calculate histograms of surrogate matrices independently and then sum.
> Change how surrogate histograms are calculated

- connPFM/connPFM.py
- connPFM/utils/surrogate_generator.py
Closes no.
- Take the absolute path of input data to get the data directory. This change allows running the command from within the data directory.
> Get data directory with absolute path

- connPFM/cli/connPFM.py
- connPFM/connPFM.py
- connPFM/connectivity/ev.py
- connPFM/debiasing/debiasing.py
- connPFM/deconvolution/roiPFM.py
- connPFM/tests/test_ev.py
- connPFM/tests/test_integration.py
- connPFM/tests/test_utils.py
- connPFM/utils/io.py
- connPFM/utils/surrogate_generator.py
Closes none.
- Adds an `io.py` file with reading and saving functions.
- Updates the CLI to support reading multiple files.
- Updates the value of the given TE to seconds if ms is given.
- The reading function can read multi-echo data and concatenates time-series of different echos in time.
> Add io file for reading a saving files, and support multi-echo

- .circleci/config.yml
- .codecov.yml
- connPFM/tests/conftest.py
- connPFM/tests/test_debiasing.py
- connPFM/tests/test_deconvolution.py
- connPFM/tests/test_utils.py
Closes #69 .
- Add ME data to osf and `conftest.py`
- Add unittest for  `stability_lars.py` using ME data
- Add unittest for `io.py` 
- Add unittest for `debiasing.py` using ME data
> Add multiecho testing for PFM

- connPFM/connPFM.py
- connPFM/debiasing/debiasing.py
- connPFM/deconvolution/compute_slars.sh
- connPFM/tests/test_debiasing.py
- connPFM/tests/test_integration.py
Closes #81  .
- `--prefix` is now use to give the path to`fitt.nii.gz` and `beta.nii.gz`
- Relative path is allowed
- Change integration --prefix option so it is done correctly
> Use --prefix option to establish the full path for the debiasing output

- connPFM/cli/connPFM.py
- connPFM/connPFM.py
- connPFM/connectivity/ev.py
Closes nothing.
- now the `-jobs` parameter controls the number of parallel processes ev_workflow uses 
- `-jobs` default is now 1
> Control number of parallel processes in ev_workflow

- connPFM/deconvolution/roiPFM.py
- connPFM/tests/test_utils.py
- connPFM/utils/surrogate_generator.py
- Avoids that the data is loaded again in the surrogate_data function
> Avoid that surrogate_generator loads the data again

- connPFM/connectivity/ev.py
- connPFM/connectivity/plotting.py
- connPFM/tests/test_ev.py
- ohbm2022/stability_pfm.py
Closes # .
- Now when doing rss thresholding, the threshold is plotted in the rss subplot
- Change stability_pfm paths for multiecho data
> Ohbm poster changes

- connPFM/connectivity/connectivity_utils.py
- connPFM/connectivity/ev.py
Closes #94  .
- Eliminates original bold singal ETS calculation
-
> Eliminate calculation of ETS on the original BOLD signal

- .circleci/config.yml
- connPFM/info.py
Closes #98 .
- Add python 3.10
- Eliminate python 3.6
> Add python 3.10 and eliminate python 3.6 from testing
